// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kamijoucen/notesync/apps/server/internal/ent/fileitem"
	"github.com/kamijoucen/notesync/apps/server/internal/ent/predicate"
)

// FileItemDelete is the builder for deleting a FileItem entity.
type FileItemDelete struct {
	config
	hooks    []Hook
	mutation *FileItemMutation
}

// Where appends a list predicates to the FileItemDelete builder.
func (fid *FileItemDelete) Where(ps ...predicate.FileItem) *FileItemDelete {
	fid.mutation.Where(ps...)
	return fid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (fid *FileItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, fid.sqlExec, fid.mutation, fid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (fid *FileItemDelete) ExecX(ctx context.Context) int {
	n, err := fid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (fid *FileItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(fileitem.Table, sqlgraph.NewFieldSpec(fileitem.FieldID, field.TypeInt))
	if ps := fid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, fid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	fid.mutation.done = true
	return affected, err
}

// FileItemDeleteOne is the builder for deleting a single FileItem entity.
type FileItemDeleteOne struct {
	fid *FileItemDelete
}

// Where appends a list predicates to the FileItemDelete builder.
func (fido *FileItemDeleteOne) Where(ps ...predicate.FileItem) *FileItemDeleteOne {
	fido.fid.mutation.Where(ps...)
	return fido
}

// Exec executes the deletion query.
func (fido *FileItemDeleteOne) Exec(ctx context.Context) error {
	n, err := fido.fid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{fileitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (fido *FileItemDeleteOne) ExecX(ctx context.Context) {
	if err := fido.Exec(ctx); err != nil {
		panic(err)
	}
}
