// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kamijoucen/notesync/apps/server/internal/ent/fileitem"
	"github.com/kamijoucen/notesync/apps/server/internal/ent/predicate"
	"github.com/kamijoucen/notesync/apps/server/internal/ent/repository"
)

// FileItemQuery is the builder for querying FileItem entities.
type FileItemQuery struct {
	config
	ctx            *QueryContext
	order          []fileitem.OrderOption
	inters         []Interceptor
	predicates     []predicate.FileItem
	withRepository *RepositoryQuery
	withParent     *FileItemQuery
	withChildren   *FileItemQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FileItemQuery builder.
func (fiq *FileItemQuery) Where(ps ...predicate.FileItem) *FileItemQuery {
	fiq.predicates = append(fiq.predicates, ps...)
	return fiq
}

// Limit the number of records to be returned by this query.
func (fiq *FileItemQuery) Limit(limit int) *FileItemQuery {
	fiq.ctx.Limit = &limit
	return fiq
}

// Offset to start from.
func (fiq *FileItemQuery) Offset(offset int) *FileItemQuery {
	fiq.ctx.Offset = &offset
	return fiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fiq *FileItemQuery) Unique(unique bool) *FileItemQuery {
	fiq.ctx.Unique = &unique
	return fiq
}

// Order specifies how the records should be ordered.
func (fiq *FileItemQuery) Order(o ...fileitem.OrderOption) *FileItemQuery {
	fiq.order = append(fiq.order, o...)
	return fiq
}

// QueryRepository chains the current query on the "repository" edge.
func (fiq *FileItemQuery) QueryRepository() *RepositoryQuery {
	query := (&RepositoryClient{config: fiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fileitem.Table, fileitem.FieldID, selector),
			sqlgraph.To(repository.Table, repository.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, fileitem.RepositoryTable, fileitem.RepositoryColumn),
		)
		fromU = sqlgraph.SetNeighbors(fiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (fiq *FileItemQuery) QueryParent() *FileItemQuery {
	query := (&FileItemClient{config: fiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fileitem.Table, fileitem.FieldID, selector),
			sqlgraph.To(fileitem.Table, fileitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, fileitem.ParentTable, fileitem.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(fiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChildren chains the current query on the "children" edge.
func (fiq *FileItemQuery) QueryChildren() *FileItemQuery {
	query := (&FileItemClient{config: fiq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fiq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fileitem.Table, fileitem.FieldID, selector),
			sqlgraph.To(fileitem.Table, fileitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, fileitem.ChildrenTable, fileitem.ChildrenColumn),
		)
		fromU = sqlgraph.SetNeighbors(fiq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FileItem entity from the query.
// Returns a *NotFoundError when no FileItem was found.
func (fiq *FileItemQuery) First(ctx context.Context) (*FileItem, error) {
	nodes, err := fiq.Limit(1).All(setContextOp(ctx, fiq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fileitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fiq *FileItemQuery) FirstX(ctx context.Context) *FileItem {
	node, err := fiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FileItem ID from the query.
// Returns a *NotFoundError when no FileItem ID was found.
func (fiq *FileItemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fiq.Limit(1).IDs(setContextOp(ctx, fiq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fileitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fiq *FileItemQuery) FirstIDX(ctx context.Context) int {
	id, err := fiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FileItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FileItem entity is found.
// Returns a *NotFoundError when no FileItem entities are found.
func (fiq *FileItemQuery) Only(ctx context.Context) (*FileItem, error) {
	nodes, err := fiq.Limit(2).All(setContextOp(ctx, fiq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fileitem.Label}
	default:
		return nil, &NotSingularError{fileitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fiq *FileItemQuery) OnlyX(ctx context.Context) *FileItem {
	node, err := fiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FileItem ID in the query.
// Returns a *NotSingularError when more than one FileItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (fiq *FileItemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = fiq.Limit(2).IDs(setContextOp(ctx, fiq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fileitem.Label}
	default:
		err = &NotSingularError{fileitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fiq *FileItemQuery) OnlyIDX(ctx context.Context) int {
	id, err := fiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FileItems.
func (fiq *FileItemQuery) All(ctx context.Context) ([]*FileItem, error) {
	ctx = setContextOp(ctx, fiq.ctx, ent.OpQueryAll)
	if err := fiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*FileItem, *FileItemQuery]()
	return withInterceptors[[]*FileItem](ctx, fiq, qr, fiq.inters)
}

// AllX is like All, but panics if an error occurs.
func (fiq *FileItemQuery) AllX(ctx context.Context) []*FileItem {
	nodes, err := fiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FileItem IDs.
func (fiq *FileItemQuery) IDs(ctx context.Context) (ids []int, err error) {
	if fiq.ctx.Unique == nil && fiq.path != nil {
		fiq.Unique(true)
	}
	ctx = setContextOp(ctx, fiq.ctx, ent.OpQueryIDs)
	if err = fiq.Select(fileitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fiq *FileItemQuery) IDsX(ctx context.Context) []int {
	ids, err := fiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fiq *FileItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, fiq.ctx, ent.OpQueryCount)
	if err := fiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, fiq, querierCount[*FileItemQuery](), fiq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (fiq *FileItemQuery) CountX(ctx context.Context) int {
	count, err := fiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fiq *FileItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, fiq.ctx, ent.OpQueryExist)
	switch _, err := fiq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (fiq *FileItemQuery) ExistX(ctx context.Context) bool {
	exist, err := fiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FileItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fiq *FileItemQuery) Clone() *FileItemQuery {
	if fiq == nil {
		return nil
	}
	return &FileItemQuery{
		config:         fiq.config,
		ctx:            fiq.ctx.Clone(),
		order:          append([]fileitem.OrderOption{}, fiq.order...),
		inters:         append([]Interceptor{}, fiq.inters...),
		predicates:     append([]predicate.FileItem{}, fiq.predicates...),
		withRepository: fiq.withRepository.Clone(),
		withParent:     fiq.withParent.Clone(),
		withChildren:   fiq.withChildren.Clone(),
		// clone intermediate query.
		sql:  fiq.sql.Clone(),
		path: fiq.path,
	}
}

// WithRepository tells the query-builder to eager-load the nodes that are connected to
// the "repository" edge. The optional arguments are used to configure the query builder of the edge.
func (fiq *FileItemQuery) WithRepository(opts ...func(*RepositoryQuery)) *FileItemQuery {
	query := (&RepositoryClient{config: fiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fiq.withRepository = query
	return fiq
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (fiq *FileItemQuery) WithParent(opts ...func(*FileItemQuery)) *FileItemQuery {
	query := (&FileItemClient{config: fiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fiq.withParent = query
	return fiq
}

// WithChildren tells the query-builder to eager-load the nodes that are connected to
// the "children" edge. The optional arguments are used to configure the query builder of the edge.
func (fiq *FileItemQuery) WithChildren(opts ...func(*FileItemQuery)) *FileItemQuery {
	query := (&FileItemClient{config: fiq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	fiq.withChildren = query
	return fiq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FileItem.Query().
//		GroupBy(fileitem.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (fiq *FileItemQuery) GroupBy(field string, fields ...string) *FileItemGroupBy {
	fiq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &FileItemGroupBy{build: fiq}
	grbuild.flds = &fiq.ctx.Fields
	grbuild.label = fileitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.FileItem.Query().
//		Select(fileitem.FieldCreateTime).
//		Scan(ctx, &v)
func (fiq *FileItemQuery) Select(fields ...string) *FileItemSelect {
	fiq.ctx.Fields = append(fiq.ctx.Fields, fields...)
	sbuild := &FileItemSelect{FileItemQuery: fiq}
	sbuild.label = fileitem.Label
	sbuild.flds, sbuild.scan = &fiq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a FileItemSelect configured with the given aggregations.
func (fiq *FileItemQuery) Aggregate(fns ...AggregateFunc) *FileItemSelect {
	return fiq.Select().Aggregate(fns...)
}

func (fiq *FileItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range fiq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, fiq); err != nil {
				return err
			}
		}
	}
	for _, f := range fiq.ctx.Fields {
		if !fileitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fiq.path != nil {
		prev, err := fiq.path(ctx)
		if err != nil {
			return err
		}
		fiq.sql = prev
	}
	return nil
}

func (fiq *FileItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FileItem, error) {
	var (
		nodes       = []*FileItem{}
		withFKs     = fiq.withFKs
		_spec       = fiq.querySpec()
		loadedTypes = [3]bool{
			fiq.withRepository != nil,
			fiq.withParent != nil,
			fiq.withChildren != nil,
		}
	)
	if fiq.withRepository != nil || fiq.withParent != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, fileitem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*FileItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &FileItem{config: fiq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, fiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := fiq.withRepository; query != nil {
		if err := fiq.loadRepository(ctx, query, nodes, nil,
			func(n *FileItem, e *Repository) { n.Edges.Repository = e }); err != nil {
			return nil, err
		}
	}
	if query := fiq.withParent; query != nil {
		if err := fiq.loadParent(ctx, query, nodes, nil,
			func(n *FileItem, e *FileItem) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	if query := fiq.withChildren; query != nil {
		if err := fiq.loadChildren(ctx, query, nodes,
			func(n *FileItem) { n.Edges.Children = []*FileItem{} },
			func(n *FileItem, e *FileItem) { n.Edges.Children = append(n.Edges.Children, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (fiq *FileItemQuery) loadRepository(ctx context.Context, query *RepositoryQuery, nodes []*FileItem, init func(*FileItem), assign func(*FileItem, *Repository)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FileItem)
	for i := range nodes {
		if nodes[i].repository_files == nil {
			continue
		}
		fk := *nodes[i].repository_files
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(repository.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "repository_files" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (fiq *FileItemQuery) loadParent(ctx context.Context, query *FileItemQuery, nodes []*FileItem, init func(*FileItem), assign func(*FileItem, *FileItem)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*FileItem)
	for i := range nodes {
		if nodes[i].file_item_children == nil {
			continue
		}
		fk := *nodes[i].file_item_children
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(fileitem.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "file_item_children" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (fiq *FileItemQuery) loadChildren(ctx context.Context, query *FileItemQuery, nodes []*FileItem, init func(*FileItem), assign func(*FileItem, *FileItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*FileItem)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.FileItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(fileitem.ChildrenColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.file_item_children
		if fk == nil {
			return fmt.Errorf(`foreign-key "file_item_children" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "file_item_children" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (fiq *FileItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fiq.querySpec()
	_spec.Node.Columns = fiq.ctx.Fields
	if len(fiq.ctx.Fields) > 0 {
		_spec.Unique = fiq.ctx.Unique != nil && *fiq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, fiq.driver, _spec)
}

func (fiq *FileItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(fileitem.Table, fileitem.Columns, sqlgraph.NewFieldSpec(fileitem.FieldID, field.TypeInt))
	_spec.From = fiq.sql
	if unique := fiq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if fiq.path != nil {
		_spec.Unique = true
	}
	if fields := fiq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fileitem.FieldID)
		for i := range fields {
			if fields[i] != fileitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fiq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fiq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fiq *FileItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fiq.driver.Dialect())
	t1 := builder.Table(fileitem.Table)
	columns := fiq.ctx.Fields
	if len(columns) == 0 {
		columns = fileitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fiq.sql != nil {
		selector = fiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fiq.ctx.Unique != nil && *fiq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range fiq.predicates {
		p(selector)
	}
	for _, p := range fiq.order {
		p(selector)
	}
	if offset := fiq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fiq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FileItemGroupBy is the group-by builder for FileItem entities.
type FileItemGroupBy struct {
	selector
	build *FileItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (figb *FileItemGroupBy) Aggregate(fns ...AggregateFunc) *FileItemGroupBy {
	figb.fns = append(figb.fns, fns...)
	return figb
}

// Scan applies the selector query and scans the result into the given value.
func (figb *FileItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, figb.build.ctx, ent.OpQueryGroupBy)
	if err := figb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FileItemQuery, *FileItemGroupBy](ctx, figb.build, figb, figb.build.inters, v)
}

func (figb *FileItemGroupBy) sqlScan(ctx context.Context, root *FileItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(figb.fns))
	for _, fn := range figb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*figb.flds)+len(figb.fns))
		for _, f := range *figb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*figb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := figb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// FileItemSelect is the builder for selecting fields of FileItem entities.
type FileItemSelect struct {
	*FileItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (fis *FileItemSelect) Aggregate(fns ...AggregateFunc) *FileItemSelect {
	fis.fns = append(fis.fns, fns...)
	return fis
}

// Scan applies the selector query and scans the result into the given value.
func (fis *FileItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, fis.ctx, ent.OpQuerySelect)
	if err := fis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*FileItemQuery, *FileItemSelect](ctx, fis.FileItemQuery, fis, fis.inters, v)
}

func (fis *FileItemSelect) sqlScan(ctx context.Context, root *FileItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(fis.fns))
	for _, fn := range fis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*fis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
